import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { CacheFirst, StaleWhileRevalidate, NetworkOnly } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// 1. Precache all static assets generated by Vite build
precacheAndRoute(self.__WB_MANIFEST || []);

// 2. Navigation handler: serve the offline fallback page if navigation request fails
const networkOnly = new NetworkOnly();
const navigationHandler = async (params) => {
  try {
    // Attempt network first
    return await networkOnly.handle(params);
  } catch (error) {
    // If network fails, serve the cached offline page
    return caches.match('/offline.html');
  }
};

registerRoute(new NavigationRoute(navigationHandler));

// 3. Caching strategies for runtime assets
// Cache JavaScript and CSS
registerRoute(
  ({ request }) => request.destination === 'script' || request.destination === 'style',
  new StaleWhileRevalidate({
    cacheName: 'static-resources',
  })
);

// Cache Images
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// Cache Fonts
registerRoute(
  ({ request }) => request.destination === 'font',
  new CacheFirst({
    cacheName: 'fonts',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 365 * 24 * 60 * 60, // 1 Year
      }),
    ],
  })
);

// 4. Force NetworkOnly for all API requests to prevent caching authenticated requests
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkOnly()
);

// 5. Existing Push Notifications listener & event handlers
self.addEventListener('push', function(event) {
  let data = {};
  try { 
    data = event.data.json(); 
  } catch (e) { 
    data = { title: 'Notification', body: 'You have a new notification.' }; 
  }

  const title = data.title || 'FreelanceFlow';
  const options = {
    body: data.body || '',
    icon: data.icon || '/icons/icon-192x192.png',
    badge: data.badge || '/icons/icon-192x192.png',
    data: data.url || '/' 
  };

  event.waitUntil(self.registration.showNotification(title, options));
});

self.addEventListener('notificationclick', function(event) {
  event.notification.close();
  const url = event.notification.data || '/';
  event.waitUntil(clients.openWindow(url));
});
